name: konsole
description: A smol & light-lightweight TUI library for Dart.
repository: https://github.com/deepraj02/konsole
version: 0.1.0

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
